stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Construindo a aplicação..."

test:
  stage: test
  script:
    - echo "Executando testes..."

deploy:
  stage: deploy
  script:
    - echo "Implantando a aplicação..."
